### ISSUE TITLE
Perhaps all the public C++ classes should be in their own namespace?

### ISSUE THREAD

**Issue by scotthunt** [adobe/zdw#8]
I'm opening this as an issue because I wanted to start a little dialog before just doing something and making a PR.

In the end perhaps it's not very important, but it seems like we should wrap everything in our own namespace.
I know that we've got a ZDW namespace in there already for a couple things.
Perhaps we want to just wrap everything in that namespace?
Or perhaps in something like adobe_zdw or adbe_zdw?  Or even a multi-level namespace like adobe::zdw?  (Maybe I should see if I can find any other adobe open source C++ code and see what's done elsewhere?)

Thoughts?  Disagreements?

**Comment by mrimer** [comment]
Thanks for proposing the idea, Scott.  I like the direction and your idea to check out whether any other open source C++ code has a convention already being established.

**Comment by scotthunt** [comment]
Sadly, I couldn't find much by the way of Adobe open source C++ projects...

That being said, I'm kind of liking adobe::zdw.

That matches protobuf, which uses: google::protobuf (and they have a google::protobuf::internal namespace also, which we might want to follow)

**Comment by mrimer** [comment]
I too like adobe::zdw, and maybe the ::internal namespace also.  Let's do it!

**Comment by mrimer** [comment]
Thanks for the changes!
Merged your PR.
Closing this issue.
